### ISSUE TITLE
App crash on open - Branch failed to initialize

### ISSUE THREAD

**Issue by avishayil** [BranchMetrics/react-native-branch-deep-linking#14]
Stack trace:

````
06-20 05:51:20.181 2801-2801/com.zuznow.geektime E/BranchSDK: Branch instance is not created yet. Make sure you have initialised Branch. [Consider Calling getInstance(Context ctx) if you still have issue.]
06-20 05:51:20.181 2801-2801/com.zuznow.geektime D/AndroidRuntime: Shutting down VM
06-20 05:51:21.023 2801-2801/com.zuznow.geektime E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.zuznow.geektime, PID: 2801
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zuznow.geektime/com.zuznow.geektime.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.branch.referral.Branch.initSession(io.branch.referral.Branch$BranchReferralInitListener, android.net.Uri, android.app.Activity)' on a null object reference
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.branch.referral.Branch.initSession(io.branch.referral.Branch$BranchReferralInitListener, android.net.Uri, android.app.Activity)' on a null object reference
                                                                       at io.branch.rnbranch.RNBranchModule.initSession(RNBranchModule.java:42)
                                                                       at com.zuznow.geektime.MainActivity.onStart(MainActivity.java:81)
                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                       at android.app.Activity.performStart(Activity.java:6253)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
06-20 05:51:21.025 609-998/system_process W/ActivityManager:   Force finishing activity com.zuznow.geektime/.MainActivity
06-20 05:51:21.327 609-998/system_process I/WindowManager: Screenshot max retries 4 of Token{e032946 ActivityRecord{2303121 u0 com.zuznow.geektime/.MainActivity t23 f}} appWin=Window{7e81b1e u0 Starting com.zuznow.geektime} drawState=4
06-20 05:51:21.327 609-609/system_process W/art: Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 300ms
06-20 05:51:21.360 609-1759/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
06-20 05:51:21.419 609-1759/system_process W/EGL_emulation: eglSurfaceAttrib not implemented
06-20 05:51:21.419 609-1759/system_process W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xd9b3f4c0, error=EGL_SUCCESS
06-20 05:51:21.830 609-632/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{2303121 u0 com.zuznow.geektime/.MainActivity t23 f}
06-20 05:51:21.978 971-1169/com.android.launcher3 W/EGL_emulation: eglSurfaceAttrib not implemented
06-20 05:51:21.978 971-1169/com.android.launcher3 W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe04ed800, error=EGL_SUCCESS
06-20 05:51:22.238 2801-2822/com.zuznow.geektime I/CrashlyticsCore: Crashlytics report upload complete: 5767BC98007B-0001-0AF1-15BDA68DEC28.cls
06-20 05:51:25.165 609-1477/system_process D/NetlinkSocketObserver: NeighborEvent{elapsedMs=1936860, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_REACHABLE}
06-20 05:51:32.112 609-632/system_process W/ActivityManager: Activity destroy timeout for ActivityRecord{2303121 u0 com.zuznow.geektime/.MainActivity t23 f}
````

**Comment by avishayil** [comment]
I found the solution, getting the context from reactActivity seems to solve that.
Setting up a PR.

**Comment by aaustin** [comment]
Thanks @avishayil !

**Comment by aaustin** [comment]
Resolved here https://github.com/BranchMetrics/react-native-branch-deep-linking/pull/15
