### ISSUE TITLE
java.lang.String cannot be cast to java.lang.Boolean at userCompletedActionOnUniversalObject for Android API below 26

### ISSUE THREAD

**Issue by wbattel4607** [BranchMetrics/react-native-branch-deep-linking#348]
I'm not really sure when this started but I'm getting this `ClassCastException` that seems to be pointing at RNBranch. This wasn't happening a month ago when I last built for Android, and it seems to happen no matter what version of `react-native-branch` I use. This only happens on devices/emulators with API level 25 or below. Everything works fine on API level 26 and above.

### Environment
`react-native: 0.55.4`
`react-native-branch: 2.3.0`

`compileSdkVersion = 27`
`buildToolsVersion = "27.0.3"`
`supportLibVersion = "27.1.1"`

### Error

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:137)
        at io.branch.rnbranch.RNBranchModule.convertMapToParams(RNBranchModule.java:1153)
        at io.branch.rnbranch.RNBranchModule.userCompletedActionOnUniversalObject(RNBranchModule.java:370)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
```
<img width="275" alt="screen shot 2018-06-08 at 7 07 38 pm" src="https://user-images.githubusercontent.com/13490339/41185569-4935517c-6b4f-11e8-9c81-55ad2e6f4165.png">

**Comment by sequoiaat** [comment]
Hi,

We're working on this.  

Are you sending any Boolean parameters with the link ? And also when the app is crashing is it during the app loading itself or on sharing?

Thanks

**Comment by wbattel4607** [comment]
@sequoiaat we are not sending any additional parameters beyond those automatically included by Branch. It was crashing while loading the app, but...

I went back to it today to try to get more information, but now it is working- and nothing was changed. Confusing, but it seems to be working. I'm going to close this issue and if it comes back I'll re-open it.

**Comment by iLyxa3D** [comment]
Found the solution in my case.

The function expects to receive an object with fields of **_string_** type, but I sent a _boolean_ or _double_. Changing the data type to a **string**, the error disappeared.

It was: 
firebase.analytics().setUserProperties({key: **boolean_value**});
Changed to:
firebase.analytics().setUserProperties({key: **string_value**});

In your case, some java function waits for a data type **string**, but you pass type **boolean**..
