### ISSUE TITLE
Module parse failed: /myApp/node_modules/react-native-branch/src/index.js Unexpected token (20:21)

### ISSUE THREAD

**Issue by FoxShinigami** [BranchMetrics/react-native-branch-deep-linking#350]
i am currently having this error when i try to build.

```
Error: ./node_modules/react-native-branch/src/index.js
Module parse failed: /myApp/node_modules/react-native-branch/src/index.js Unexpected token (20:21)
You may need an appropriate loader to handle this file type.
| 
| class Branch {
|   nativeEventEmitter = Platform.select({
|     android: DeviceEventEmitter,
|     ios: new NativeEventEmitter(RNBranchEventEmitter)
 @ ./src/pages/saldo/saldo.ts 24:0-41
 @ ./src/pages/saldo/saldo.module.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/module.js
 @ ./node_modules/ionic-angular/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at new BuildError (/myApp/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/myApp/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/myApp/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/myApp/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/myApp/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/myApp/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/myApp/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/myApp/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/myApp/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/myApp/node_modules/webpack/lib/Compiler.js:365:9)
```

if i remove the "import branch, { BranchEvent } from 'react-native-branch' " it works. 

anything more i can provide to help identify the problem?

Thanks.

**Comment by sequoiaat** [comment]
@FoxShinigami 

Can you please share your version info,
1. react-native branch version
2. react-native version
3. node version
 
Thanks

**Comment by FoxShinigami** [comment]
1)react-native-branch: ^2.3.0
2)react-native: ^0.55.4
3)node: v6.14.1

thanks for the fast answer.

**Comment by sequoiaat** [comment]
@FoxShinigami  - We are trying to reproduce this issue but not able to see it at our end. Is there anything we are missing  ?

**Comment by FoxShinigami** [comment]
currently i am using ionic to develop the project. when i fist tried branch with the simple feature to open the home or go to the specified website, it worked. the app opened and/or the web page opened. however when i started the [https://docs.branch.io/pages/apps/react-native/#implement-features](url). The "import branch, { BranchEvent } from 'react-native-branch'" made the error occur. 

my package.json

```
{
 
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@ionic-native/camera": "^4.3.3",
    "@ionic-native/core": "^4.5.2",
    "@ionic-native/device": "^4.4.2",
    "@ionic-native/diagnostic": "^4.5.2",
    "@ionic-native/facebook": "^4.4.0",
    "@ionic-native/geolocation": "^4.4.2",
    "@ionic-native/google-analytics": "^4.5.2",
    "@ionic-native/google-maps": "^4.5.3",
    "@ionic-native/local-notifications": "^4.4.2",
    "@ionic-native/location-accuracy": "^4.5.2",
    "@ionic-native/native-page-transitions": "^4.5.2",
    "@ionic-native/push": "^4.4.2",
    "@ionic-native/screenshot": "^4.5.3",
    "@ionic-native/social-sharing": "^4.5.2",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "^4.5.2",
    "@ionic/cloud-angular": "^0.12.0",
    "@ionic/storage": "2.0.1",
    "angular2-swing": "^0.14.0",
    "brmasker-ionic-3": "^1.0.10",
    "com.darktalker.cordova.screenshot": "^0.1.6",
    "com.telerik.plugins.nativepagetransitions": "^0.6.5",
    "cordova-android": "6.3.0",
    "cordova-browser": "5.0.3",
    "cordova-plugin-badge": "^0.8.7",
    "cordova-plugin-camera": "^2.4.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-geolocation": "^3.0.0",
    "cordova-plugin-google-analytics": "^1.8.3",
    "cordova-plugin-googlemaps": "^2.1.1",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "^2.4.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.2.1",
    "cordova-sqlite-storage": "^2.2.0",
    "cordova.plugins.diagnostic": "^3.9.2",
    "dateformat": "^3.0.2",
    "es6-promise-plugin": "^4.1.0",
    "ionic-angular": "3.7.1",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "minimist": "^1.2.0",
    "ngx-qrcode2": "0.0.5",
    "phonegap-plugin-push": "^2.1.2",
    "react-native": "^0.55.4",
    "react-native-branch": "^2.3.0",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "xml2js": "^0.4.19",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.2",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "typescript": "^2.9.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-camera": {
        "CAMERA_USAGE_DESCRIPTION": " ",
        "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
      },
      "cordova-plugin-statusbar": {},
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-facebook4": {
        "APP_ID": "***",
        "APP_NAME": "***"
      },
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-local-notification": {},
      "phonegap-plugin-push": {
        "SENDER_ID": "***",
        "FCM_VERSION": "11.0.1"
      },
      "cordova.plugins.diagnostic": {},
      "cordova-plugin-google-analytics": {},
      "com.darktalker.cordova.screenshot": {},
      "cordova-plugin-googlemaps": {
        "API_KEY_FOR_ANDROID": "***",
        "API_KEY_FOR_IOS": "***",
        "PLAY_SERVICES_VERSION": "11.0.1"
      },
      "branch-cordova-sdk": {}
    },
    "platforms": [
      "android",
      "browser"
    ]
  }
}

```

ths

**Comment by sequoiaat** [comment]
@FoxShinigami 

You are currently working on ionic project. 
Whereas the document link that you are referring is of react-native. You are trying to import react-native branch sdk in ionic project which is incorrect.

For ionic project, Please refer this link: https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#implement-features and the git project is  https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#features 

Thanks

**Comment by FoxShinigami** [comment]
hadn't noticed Sorry. Thanks for the help.

**Comment by stepupithub** [comment]
l;';l

**Comment by stepupithub** [comment]
Error: Module parse failed: /home/stepupit/Documents/rajnikant-ionic/Buy-Sell/node_modules/@ionic/app-scripts/dist/webpack/loader.js!/home/stepupit/Documents/rajnikant-ionic/Buy-Sell/src/providers/global/global.ts Unexpected token (21:10)
You may need an appropriate loader to handle this file type.
