### ISSUE TITLE
Android: Crash in _onInitSessionResult

### ISSUE THREAD

**Issue by cmcewen** [BranchMetrics/react-native-branch-deep-linking#50]
Seen this crash 3 times so far

```
Fatal Exception: com.facebook.react.common.JavascriptException: null is not an object (evaluating 'e.params'), stack:
_onInitSessionResult@571:691
value@80:1344
value@34:3798
<unknown>@34:1955
p@34:617
value@34:1927
```

**Comment by bhaskarmurthy** [comment]
:1

**Comment by rt2zz** [comment]
I see where the error is coming from. Going to handle it in the js side, and also try to figure out under what circumstances it receives a null object.

Will cut a new release later today with fix.

**Comment by seque1990** [comment]
I got `_initSessionResult: null` today too. It's working in a different branch that I was working, but once I tried to rebase to `master` I start getting that. I think it could be somehow related to the setup process.

**Comment by avishayil** [comment]
Another doc on this:
````
Fatal Exception: com.facebook.react.common.JavascriptException: null is not an object (evaluating 'e.params'), stack:
<unknown>@12:633
<unknown>@575:670
_onInitSessionResult@575:649
value@87:1344
value@62:3800
<unknown>@62:1962
y@62:623
value@62:1934

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:810)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:209)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
````

**Comment by joyeon** [comment]
+1

**Comment by drop-dan** [comment]
You can avoid this issue for now by making sure any callbacks you pass to subscribe don't assume that result is an object.

bad:
```branch.subscribe(({ params, error, uri }) => { /* do stuff */})```

good:
```branch.subscribe((result) => { /* do stuff with result if it isn't null */})```

**Comment by aaustin** [comment]
Yes and this is the recommended code usage. Please make sure to add your null checks:
```
branch.subscribe(({params, error, uri}) => {
  if (params) { /* handle branch link */ }
  else { /* handle uri */ }
})
```

**Comment by aaustin** [comment]
actually my bad - the docs are pretty unclear. Let me clean them up.

**Comment by aaustin** [comment]
I updated the snippet in all docs to this:
```branch.subscribe((bundle) => {
  if (bundle && bundle.params && !bundle.error) {
    // grab deep link data and route appropriately.
  }
})```

Sorry for the misleading docs!
