### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"

### ISSUE THREAD

**Issue by adrienthiery** [BranchMetrics/react-native-branch-deep-linking#54]
Hi there,

I'm totally blocked on a bug. 
For introduction, I'm originally a Full stack developer and I do not know much in Native so sorry in advance if that is something obvious, I spent already more than 2 days on this... 😞 

After upgrading RN to the 0.36.1, I have the following error when using `react-native-branch`:
```
E/AndroidRuntime(32497): java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
E/AndroidRuntime(32497): 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:260)
E/AndroidRuntime(32497): 	at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:627)
E/AndroidRuntime(32497): 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
E/AndroidRuntime(32497): 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
E/AndroidRuntime(32497): 	at com.myproject.MainActivity.onActivityResult(MainActivity.java:32)
E/AndroidRuntime(32497): 	at android.app.Activity.dispatchActivityResult(Activity.java:6549)
E/AndroidRuntime(32497): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4054)
E/AndroidRuntime(32497): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4101)
E/AndroidRuntime(32497): 	at android.app.ActivityThread.access$1400(ActivityThread.java:177)
E/AndroidRuntime(32497): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1497)
E/AndroidRuntime(32497): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(32497): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(32497): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
E/AndroidRuntime(32497): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32497): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32497): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(32497): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

This is obviously linked to the [Activity attribute addition in onActivityResult](https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35) in RN v0.33 but I don't know what to do/if I can do something on `react-native-branch` itself to fix it... I think it goes deeper in Branch's SDK

Environment:

* React Native version: 0.36.1
* Platform: Android
* Operating System: MacOS 10.12.1

**Comment by adrienthiery** [comment]
😞  Actually, sorry, not an issue with your package....

**Comment by rt2zz** [comment]
@adrienthiery Glad you got it sorted! do you mind sharing what the issue was in case others come across similar?

**Comment by adrienthiery** [comment]
The issue was in another package: `react-native-image-picker` and was linked to my update of react-native to RN0.36
